### ISSUE TITLE
Custom Enum Class Support

### ISSUE THREAD

**Issue by brcbydr** [hamzaahmedkhan/SpinnerDialog#11]
Hi all,

First of all thanks for the library :)

I have implemented SpinnerDialog but want to work with my enum classes. What is the best way to do this?

Thanks in advance!

**Comment by brcbydr** [comment]
I added converter object to convert my spinner enums to ArrayList<SpinnerModel> like below:

`object SpinnerModelConverter {
    fun toX(): ArrayList<SpinnerModel> {
        val model: ArrayList<SpinnerModel> = ArrayList()
        for (item in X.values()) {
            val text = App.context?.getString(item.stringResId)
            text.let { model.add(SpinnerModel(it!!)) }
        }
        return model
    }
}`

What do you think about this solution?

By the way SpinnerModel's id is always 0. I think not implemented yet, right?

**Comment by hamzaahmedkhan** [comment]
Hi,
For now you have to pass ArrayList of SpinnerModel because in future I'll add description and image support too.
For enums, you'll eventually have to convert it into String to display it in adapter. So you'll have to map your enum value into SpinnerModel 'text' field. You can just override toString in your enum property and then to convert it to String.

```
enum class TestEnum {

    ENUM1 {
        override fun toString(): String {
            return "enum1"
        }
    },

    ENUM2 {
        override fun toString(): String {
            return "enum2"
        }
    }
}

```

Usage:

      
```
        // initialize spinner ArrayList

        val spinnerData: ArrayList<SpinnerModel> = ArrayList()


        // If you want to set enum individually
        val choice1 = TestEnum.ENUM1
        val choice2 = TestEnum.ENUM2

        spinnerData.add(SpinnerModel(choice1.toString()))
        spinnerData.add(SpinnerModel(choice2.toString()))


        // If you want to set all enums values in Spinner
        TestEnum.values().forEach {
            spinnerData.add(SpinnerModel(it.toString()))
        }
```


> By the way SpinnerModel's id is always 0. I think not implemented yet, right?

for id, developers can set id if they want to, just like description. In SpinnerModel the only mandatory field is 'text'. I might add few more properties in future enhancement.

Hope this will help you.

**Comment by hamzaahmedkhan** [comment]
I've updated the docs too. If you face any problem, I'll reopen this issue again.
